[package]
name = "rust-basics"
version = "0.1.0"
authors = ["Moses Christopher Bollavarapu <moseschristopherb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
